# Generated by Django 4.0.1 on 2022-04-14 18:39

import django.core.validators
from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('shortened_link', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=5, max_length=5, prefix='', primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=30, unique=True, validators=[django.core.validators.URLValidator()])),
                ('visits_count', models.IntegerField(default=0)),
                ('user_ip', models.CharField(max_length=18, null=True, validators=[django.core.validators.validate_ipv4_address])),
                ('user_agent', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
